const { game } = require('./load.js');
const G = game('reaction_rps.js'); const T = G.test;
let bad = 0; const ok = (c, m) => { if (!c) { bad++; console.log('FAIL', m); } };
ok(T.judge('rock', 'scissors') === 1 && T.judge('scissors', 'paper') === 1 && T.judge('paper', 'rock') === 1, 'wins');
ok(T.judge('scissors', 'rock') === -1 && T.judge('paper', 'scissors') === -1 && T.judge('rock', 'paper') === -1, 'losses');
ok(T.judge('rock', 'rock') === 0 && T.judge('paper', 'paper') === 0 && T.judge('scissors', 'scissors') === 0, 'ties');
const cnt = { scissors: 0, rock: 0, paper: 0 }; const N = 30000;
for (let i = 0; i < N; i++) cnt[T.randomKind()]++;
console.log(JSON.stringify(cnt)); ok(Object.values(cnt).every(c => Math.abs(c / N - 1 / 3) < 0.015), 'uniform');
console.log(T.chanceText(0) === '', T.chanceText(1), T.chanceText(5), T.chanceText(12));
console.log(bad ? 'FAILED ' + bad : 'ALL PASS');
